token_size: 768
patch_size: 4
in_chans: 3
depths: [2,2,6,2]
num_heads: [3,6,12,24]
drop_path_rate: 0.2
num_heads_fusion: [1,1,1,1]
layer_configs:
  mlp_ratio: 4.0
  proj_drop: 0.0
  attn_drop: 0.0
  fusion_drop: 0.0